### ISSUE TITLE
ImageToTextTask request captcha_link with untrusted SSL certificate.

### ISSUE THREAD

**Issue by benvindo** [AndreiDrang/python3-anticaptcha#12]
I need get images by site with untrusted SSL certificate, in a common request I pass 'verify=False' in get of request.

There is some way get images by site with untrusted SSL certificate?

**Comment by AndreiDrang** [comment]
Hi!
Yes, of course, you need just:
`result = ImageToTextTask.ImageToTextTask(anticaptcha_key=ANTICAPTCHA_KEY) .captcha_handler(captcha_link='some_link',  verify = False)`
P.s. I think we need to add more examples ..

**Comment by benvindo** [comment]
Hello,

So, When I tried put parameter 'verify = False' in captcha_handler, I received this error:

IdGetError: 
 Пораждается при ошибке получения ID капчи от сервиса. Ответ сервера:

 {'errorId': 3, 'errorCode': 'ERROR_ZERO_CAPTCHA_FILESIZE', 'errorDescription': 'The size of the captcha you are uploading is less than 100 bytes'}

Code bellow:
```
image_link = "https://sipa.inss.gov.br/SipaINSS/api/imagem?d=I_60fa7b73-a494-4081-a1ce-f9e797387130_DB4A0BA13A6B26C1A0087B4BDE7288C0.lbroute_v131p040_internet"
# Возвращается строка-расшифровка капчи. Get string for solve captcha, and some other info.
user_answer = ImageToTextTask.ImageToTextTask(anticaptcha_key = ANTICAPTCHA_KEY).captcha_handler(captcha_link=image_link, verify = False)

print(user_answer)
```

**Comment by benvindo** [comment]
Yes, link bellow:

https://sipa.inss.gov.br/SipaINSS/pages/consit/consitInicio.xhtml

**Comment by AndreiDrang** [comment]
![image](https://user-images.githubusercontent.com/16991365/40388488-60595d60-5e18-11e8-99c3-3ed9e302edb9.png)
Bad news :)
Okay, library can't download image, try add to `captcha_handler` some cookies/header/other [`requests`](http://docs.python-requests.org/en/master/user/quickstart/) params.

**Comment by benvindo** [comment]
Okay, I'll try add others params in request.

**Comment by benvindo** [comment]
Hey,

I believe I tried every possible way to add more params in _captcha_handler_ but the library continues giving me same error :/

My code test:
```
image_link = "https://sipa.inss.gov.br/SipaINSS/api/imagem?d=I_946b3fa6-9796-4509-a8fe-c63a68835b9b_6FBFD2CF5556C06EFBF485588F77ABC6.lbroute_v131p040_internet&amp;uId=1527080962508"
img_link="https://sipa.inss.gov.br/SipaINSS/pages/consit/consitInicio.xhtml"

headers = {
            'Host': 'sipa.inss.gov.br',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0',
            'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
            'Accept-Language': 'pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3',
            'Accept-Encoding': 'gzip, deflate, br',
            'Referer': 'https://sipa.inss.gov.br/SipaINSS/pages/consit/consitInicio.xhtml',
            'Cookie': 'JSESSIONID="YjJ3eUWnCf24mZOembsjjMMT.slave1:server-sipa"',
            'Connection': 'keep-alive'
          }
proxies = {
    "http": 'http://191.34.80.133:8080', 
    "https": 'http://191.34.80.133:8080'
}
payload = "d=I_20091a23-70f8-4c99-a744-a48484588fd4_696D39F6650C5D348D72FD5693E9D3F1.lbroute_v131p041_internet&amp;uId=1527080676318"

user_answer = ImageToTextTask.ImageToTextTask(anticaptcha_key = ANTICAPTCHA_KEY).captcha_handler(captcha_link=img_link, verify=False, proxies=proxies, data=payload, headers=headers)

print(user_answer)
```

**Comment by AndreiDrang** [comment]
> Could it be something related to the image format?

Yes, library use **.png** format for images.
Try to download captcha-image with own script and than **encode image with base64**, and put it in **python3-anticaptcha** library(set param `.captcha_handler(captcha_base64=%YOUR_base64_STRING%)`). 

You can encode image with **base64** library and code like this:
`base64.b64encode(%IMAGE_HERE%).decode('utf-8')`

**Comment by benvindo** [comment]
I tried send the image in format **base64** but return this error:

> ParamError: 
> Пораждается, при передаче неверного параметра.Wrong 'save_format' parameter. Valid formats: 'const' or 'temp'.
> 
> Неправильный 'save_format' параметр. Возможные форматы: 'const' или 'temp'.

So I get your exemplo of base64 e tried run but return same error, Can you check this?

**Comment by AndreiDrang** [comment]
1. Clone it from git and install(later i will update library on PyPi);
2. U send wrong param, your request mustlook like:
https://github.com/AndreiDrang/python3-anticaptcha/blob/2b8ff6efd798ecdf692aad96b0ccad15279da7ac/anticaptcha_examples/anticaptcah_image_to_text_example.py#L35

**Comment by benvindo** [comment]
Now it's working, thanks for the help :)

**Comment by AndreiDrang** [comment]
No problem 😊
