### ISSUE TITLE
поправьте

### ISSUE THREAD

**Issue by arkadybag** [AndreiDrang/python3-anticaptcha#13]
https://github.com/AndreiDrang/python3-anticaptcha/blob/c1b54a6a43677cc2aebaf363d917b9a8dfb98383/python3_anticaptcha/config.py#L18

я даже не могу описать уровень моего недовольства этим куском кода. Надеюсь вы понимаете, что это дно

**Comment by AndreiDrang** [comment]
Доброго времени суток.
Библиотека открытая - если у Вас есть предложения по ее улучшению, Вы всегда можете их внести, сделав "Pull Request"

**Comment by arkadybag** [comment]
ok
