### ISSUE TITLE
Wrong errors.py file packed in dist/python3-anticaptcha-1.2.1.tar.gz

### ISSUE THREAD

**Issue by maximium** [AndreiDrang/python3-anticaptcha#36]
**Describe the bug**
python3_anticaptcha/errors.py file in git and distribution archive are different.

**To Reproduce**
0. You're in your python3-anticaptcha repo dir
1. git checkout 1.2.1
2. tar xzf dist/python3-anticaptcha-1.2.1.tar.gz -C /tmp/unpacked_dist
3. diff /tmp/unpacked_dist/python3_anticaptcha/errors.py python3_anticaptcha/errors.py

**Comment by AndreiDrang** [comment]
Thanks!
Fixed in version 1.2.2
