### ISSUE TITLE
NoCaptchaTaskProxyless - ResourceWarning

### ISSUE THREAD

**Issue by slikker09** [AndreiDrang/python3-anticaptcha#43]
When I execute several processes to resolve recaptchas, I am issued this warning and it continues to work.

/python3.6/site-packages/python3_anticaptcha/NoCaptchaTaskProxyless.py:98: ResourceWarning: unclosed <socket.socket fd=23, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('xxx.xxx.xxx.xxx', 52936), raddr=('209.212.146.169', 443) 
result_payload=self.result_payload, sleep_time=self.sleep_time

- OS: Debian 9
- Python 3.6.4
- python3-anticaptcha     1.2.5
- requests                2.21.0
- aiohttp                 3.5.4
- pika                    1.0.1

**Comment by AndreiDrang** [comment]
Thanks for issue.
I will fix it and update library.

P.s. Can u show source code for tests?
