### ISSUE TITLE
How to use with Selenium and Chrome

### ISSUE THREAD

**Issue by MacMarde** [AndreiDrang/python3-anticaptcha#45]
###Short description of trouble. Краткое описание проблемы
I want to login in to the site swagbucks.com.
###Full description of trouble. Полное описание проблемы.
I guess I need to Inject/send the result token in some way to make it work.
Any help how to use the result token with selenium/chrome?

**Comment by AndreiDrang** [comment]
1. It is not library-relative question. It is Selenium web-browser question;
2. I can't open this site;
3. I think u must use some library(like `requests`) and send token to site, then in Selenium just use cookies;
4. U can ask google `selenium post request` or smth like this.
