### ISSUE TITLE
Token - Form submission returning "captcha wrong"  

### ISSUE THREAD

**Issue by adrianomaia** [AndreiDrang/python3-anticaptcha#53]
First, thank's for this library. 

I'm using the following code to bypass a "**Recaptcha**":

                    ANTICAPTCHA_KEY = ''
                    PAGE_URL = url
                    SITE_KEY = site_key

                    result = NoCaptchaTaskProxyless.NoCaptchaTaskProxyless(anticaptcha_key = ANTICAPTCHA_KEY)\
                    .captcha_handler(websiteURL=PAGE_URL,
                                 websiteKey=SITE_KEY)
                    captcha_answer = result.get("solution").get("gRecaptchaResponse")
                    if captcha_answer != "":
                        print(captcha_answer)
                        self.driver.execute_script("document.getElementById('g-recaptcha-response').focus()")
                        time.sleep(2)
                        self.driver.execute_script("document.getElementById('g-recaptcha-response').innerHTML='%s'" % captcha_answer)
                        time.sleep(2)
                        nextBtn = self.driver.find_element_by_xpath("//input[@value='Avançar']")
                        nextBtn.click()

Problem: After click the button to submit the form, the page returns an error concerning the "**Captcha wrong**".

Can someone help me ?

**Comment by AndreiDrang** [comment]
Hi
1. Change and hide your `anticaptcha_key`, cause smb else can use it and spend your money.
2. Usually if u need solve recaptcha u need make recaptcha `textarea` visible and then insert captcha-response in it, and only after this steps click button to submit some action(like form send and etc.)
U can find example [here](https://github.com/AndreiDrang/python3-anticaptcha/blob/master/anticaptcha_examples/selenium_recaptcha_v2.py).

**Comment by adrianomaia** [comment]
Hello @AndreiDrang, than's for the answer. 

I'm inserting the **token** with this section of the code: 

`self.driver.execute_script("document.getElementById('g-recaptcha-response').innerHTML='%s'" % captcha_answer)`

Work's just fine. When I submit the form, returns the error "**Wrong Captcha**"

**Comment by AndreiDrang** [comment]
Can u give link on page with recaptcha?
U can check something:
Open page with captcha(manually), than start captcha solving process(with service), get key and try insert it(also manually) and press submit button. Is it working well?

**Comment by adrianomaia** [comment]
Also not working that way (but that's normal, because the token varies from recaptcha to recaptcha, right?). 
The link is: (https://www.detran.sp.gov.br/wps/portal/portaldetran/cidadao/veiculos/servicos/pesquisaDebitosRestricoesVeiculos/!ut/p/z1/pZJfb4IwFMU_yx54lN7agmXJsjBFEdHF-b8vpiJqNwFT0e7jD_Y2dU6zm740-Z1z23Mv4miKeCqOci1ymaViW9xn3J4TCgPnBbsAwZCAy2qdMQ5dwmyCJicA8VkBvA19NwQM1Eb8P_oWvVPPvHGz1JMm9l6r0IHb9EEf6r7PqmELN-rgOpR220GHgENu08Mv5cK9_z8D-HX7CeInLc4ncBUoI_4JXMjwG7gW0l_PDBCXi8TUUWKCSaFmW4QRh1rUpgzXyjVz0wVha8RVvIpVrMyDKrZvk-e7_aMBBmitTZ2pD5EKM8oSA2S6yD4NiJTQ21hVlnGuRGqAWCop0qySCCkq9Llwe1KZ2OexutRkk-1zND3xRrNiJhjPKXY8jOvQhVFIoN_v9sYYegDUQgM0axSH6sjTaJeMypqCbL9b22O46rUfvgC-81L0/dz/d5/L2dBISEvZ0FBIS9nQSEh/p0/IZ11_419E11C0M0UL30QQMNV10N0045=CZ6_340S9B1A00JT30A87KV1LA3863=LA0=Ejavax.servlet.include.path_info!QCPpagesQCPdebitosRestricoesTerceirosQCPpesquisaView.xhtml==/#Z11_419E11C0M0UL30QQMNV10N0045)

In order to see the content, you need to put your browser language to PT-BR.

**Comment by AndreiDrang** [comment]
> Also not working that way (but that's normal, because the token varies from recaptcha to recaptcha, right?).

Bad news, u do smth wrong.
Your recaptcha solution key must be valid 120sec after receiving (as i remember).

I will check your link bit later.

**Comment by adrianomaia** [comment]
I don't understand what I did wrong. 
I follow all the steps, try with two different api_keys, and nothing seems to work. 

The returned token never works. 
I also tried another API, same result.

**Comment by adrianomaia** [comment]
Any news ?

**Comment by AndreiDrang** [comment]
Hi
Nope, try connect to this web site and get white page without any data.
Use proxy, change language in browser.

**Comment by adrianomaia** [comment]
Just change your default language to PT-BR, and the data will appear.

**Comment by AndreiDrang** [comment]
Okay, I just need to delete all my other languages.
But all is working fine.
Make textarea visible
Get captcha solution
Insert solution
--->
![image](https://user-images.githubusercontent.com/16991365/69564186-97521600-0fc3-11ea-8c58-65ae17dbf00c.png)
Press submit button
--->
![image](https://user-images.githubusercontent.com/16991365/69564161-8d301780-0fc3-11ea-8de3-a0188dab774b.png)

**Comment by adrianomaia** [comment]
It's giving you the "Wrong Captcha" error: red alert

**Comment by AndreiDrang** [comment]
Message from the first screen is error from my old try, after this, i receive the 
second screen with other error(not captcha, as i understand).
<img width="1064" alt="Screen Shot 2019-11-26 at 7 46 55 PM" src="https://user-images.githubusercontent.com/16991365/69654334-a6999800-1085-11ea-9e03-a01b579ea4a9.png">

**Comment by adrianomaia** [comment]
you use my code?

**Comment by adrianomaia** [comment]
Can you share the code you use ?

**Comment by AndreiDrang** [comment]
Nope, I just test this method:
> Open page with captcha(manually), than start captcha solving process(with service), get key and try insert it(also manually) and press submit button. Is it working well?

If it works - code must work fine if it doesn't work - u need to check your keys/urls and etc.

**Comment by AndreiDrang** [comment]
To solve recaptcha i use code from example.

**Comment by adrianomaia** [comment]
Ok, thank you for your time.

**Comment by adrianomaia** [comment]
> To solve recaptcha i use code from example.
> 
> * get captcha solving key

Where is this example  ? Sorry, not finding him.

**Comment by AndreiDrang** [comment]
U can use any:
[First](https://github.com/AndreiDrang/python3-anticaptcha/blob/master/anticaptcha_examples/anticaptcha_nocaptcha_example.py)
[Second](https://github.com/AndreiDrang/python3-anticaptcha/blob/master/anticaptcha_examples/selenium_recaptcha_v2.py#L26)

**Comment by adrianomaia** [comment]
Did you use `NoCaptchaTask` or `NoCaptchaTaskProxyless` ?

**Comment by AndreiDrang** [comment]
I use `Proxyless` cause I didn't need any proxy.

**Comment by adrianomaia** [comment]
Last question, which like did you use do bypass the recapactha ? 

`https://www.google.com/recaptcha/api2/demo` -> this one pointing to the google demo or the one from the website ?

**Comment by AndreiDrang** [comment]
I use link to page with captcha.
For **your captcha** i use **your link**.

**Comment by adrianomaia** [comment]
I understand what I was doing wrong.... 

I was using the link for the `captcha` instead I was suppose to use the link for the `website` containing the captcha.

Thank you for you patience and for this amazing library.
