### ISSUE TITLE
site key is always wrong

### ISSUE THREAD

**Issue by iraizo** [AndreiDrang/python3-anticaptcha#55]
###Short description of trouble. Краткое описание проблемы.
Site key always wrong
###Full description of trouble. Полное описание проблемы.
the site key is always wrong when trying to get the captcha_key `        answer = ReCaptchaV3TaskProxyless.ReCaptchaV3TaskProxyless(anticaptcha_key=anticaptchakey)\
            .captcha_handler(
                websiteURL="https://discordapp.com/register",
                websiteKey="6Lef5iQTAAAAAKeIvIY-DeexoO3gj7ryl9rLMEnn",
                minScore=0.3,
                pageAction="link_page",
            )`

**Comment by AndreiDrang** [comment]
Hi!
Why did u think that it is ReCaptchav3?
For more info about ReCaptchaV3 read this description:
https://2captcha.com/2captcha-api#solving_recaptchav3

Discord registry page use usual ReCaptchaV2, change your method and all must work great.

**Comment by iraizo** [comment]
> Hi!
> Why did u think that it is ReCaptchav3?
> For more info about ReCaptchaV3 read this description:
> https://2captcha.com/2captcha-api#solving_recaptchav3
> 
> Discord registry page use usual ReCaptchaV2, change your method and all must work great.

I thought because sometimes the captcha resolves just with clicking it, i guess I was wrong, thank you
