### ISSUE TITLE
Solving Captcha with auto submit

### ISSUE THREAD

**Issue by SohamKaranjikar** [AndreiDrang/python3-anticaptcha#59]
How do we go about solving a captcha that doesnt have a final submit button but rather checks by itself if captcha is solved and then finished sign up:

website I am reffering to: https://www.roblox.com/account/signupredir

Thanks

**Comment by AndreiDrang** [comment]
![Screenshot_20200426-005606](https://user-images.githubusercontent.com/16991365/80291730-cd551b00-8758-11ea-896c-e6855e6a2a10.png)
Did u mean this captcha? But it is give u button, after u click on rotate buttons.

**Comment by SohamKaranjikar** [comment]
Yeah it does give done button, but that button as well as verify button is hidden and not accesible via selenium

**Comment by SohamKaranjikar** [comment]
any update?

**Comment by AndreiDrang** [comment]
Yep.
AntiCaptcha have worst method description i ever read.
Here is better:
https://2captcha.com/2captcha-api#solving_funcaptcha_new

But i not find how to skip captcha window and pass it.

2captcha have other good method for RotateCaptcha solving:
https://2captcha.com/2captcha-api#solving_rotatecaptcha
U just need send images and then click on left/right arrow by coordinates.

**Comment by SohamKaranjikar** [comment]
Yeah but those buttons are visually hidden and selenium cannot click on them afaik. Maybe clicking by coordinates will work, will try and update.

For anyone else trying to bypass funcaptcha I am having a little success with saving cookies after manually completing a captcha and saving them. Then next time you open an instance of selenium, use those cookies. Maybe a potential cheap and fast solution.
