### ISSUE TITLE
Posting Request With Selenium

### ISSUE THREAD

**Issue by Astrantia** [AndreiDrang/python3-anticaptcha#9]
Hello and thanks for this wrapper. I've tried to post the request I get using Selenium, but the webpage is unaffected. Am I doing something wrong?
```python
from seleniumrequests import Firefox
DRIVER = Firefox()
DRIVER.request('POST', PAGE_URL, data={'g-recaptcha-response': user_answer})
```
where page url, and user answer are correctly defined.
Printing response gives me 200, but when I check selenium, the captcha isn't solved.

**Comment by AndreiDrang** [comment]
Hi
I need your page with recaptcha.
Maybe u must send some additional "data", not only "recaptcha-response".
Ty

**Comment by sulkhanp** [comment]
@AndreiDrang I sent the page to you via email. Thanks for the response

**Comment by AndreiDrang** [comment]
Unfortunately, no solution was found
