### ISSUE TITLE
Can You do Python library for Captchaai?

### ISSUE THREAD

**Issue by sxdfgnb** [AndreiDrang/python3-anticaptcha#91]
Hi,

Can You do Python library for Captchaai? Docs can be found here https://captchaai.com/api-docs.php

 CaptchAI is already available in many Software Captcha options like GSA SER.  Also, They have a ready Referral Program. The ratio is from 10% to 20%.

So it is a win-win situation for all
Thanks

**Comment by sxdfgnb** [comment]
@AndreiDrang

**Comment by AndreiDrang** [comment]
Hi
Okay, i will check this service.
